name: Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (UTC)

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write  # Needed for removing labels
    steps:
      - uses: actions/stale@v9
        with:
          debug-only: true
          enable-statistics: true
          # PAT for GitHub API authentication
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Max number of operations per run
          operations-per-run: 1000
          # Order to get issues (not relevant here)
          ascending: true

          # ISSUES
          # Do not auto-close an issue if it is assigned to a milestone
          exempt-all-issue-milestones: true
          # Exempt all issues with assignees from stale
          exempt-all-issue-assignees: true
          
          # Only target issues with "Waiting for response" label
          only-labels: "Waiting for response"
          
          # Check for reactions in addition to comments/edits - Doesnot work
          # exempt-no-reactions: true
          
          #Remove stale label from issues on updates/comments
          remove-stale-when-updated : true
          # Idle days before marking "Waiting for response" as stale
          days-before-issue-stale: 1  # Changed to 1 day///14 days
          # Idle days before closing stale issue (after "stale" label)
          days-before-issue-close: 2  # Changed to 2 days
          # Label to apply on staled issues
          stale-issue-label: "stale"
          # Close reason (not strictly necessary)
          close-issue-reason: not_planned
          # Remove stale label on updates
          remove-issue-stale-when-updated: true
          # Stale issue message (customize if needed)
          stale-issue-message: "This issue is marked stale because it has no response for 14 days."
          # Close issue message (customize if needed)
          close-issue-message: "This issue was closed as it remained inactive for 19 days after being marked stale."
